import pandas as pd

examples = {
    'Sea': 'We went for a swim in the sea.',
    'Ocean': 'The Pacific Ocean is the largest ocean on Earth.',
    'Wave': 'A huge wave crashed against the shore.',
    'Tide': 'The tide is coming in, so we should move our towels.',
    'Beach': 'They spent the whole day relaxing on the beach.',
    'Shore': 'We walked along the shore, collecting seashells.',
    'Coast': 'The coast of California is very beautiful.',
    'Coral': 'The coral reefs are teeming with colorful fish.',
    'Reef': 'The boat carefully navigated around the reef.',
    'Marine': 'Marine biology is the study of ocean life.',
    'Saltwater': 'Many fish species can only survive in saltwater.',
    'Seawater': 'Seawater contains various dissolved minerals.',
    'Seaweed': 'The beach was covered in seaweed after the storm.',
    'Shell': 'She found a beautiful shell on the sand.',
    'Seagull': 'A seagull swooped down and stole my sandwich.',
    'Buoy': 'The red buoy marks the safe channel for boats.',
    'Pier': 'People were fishing off the end of the pier.',
    'Harbor': 'The ship slowly sailed into the harbor.',
    'Lighthouse': 'The lighthouse guides ships safely during the night.',
    'Sailboat': 'They rented a sailboat for the afternoon.',
    'Yacht': 'He invited us to a party on his luxury yacht.',
    'Cruise ship': 'The cruise ship can carry over 3,000 passengers.',
    'Fisherman': 'The fisherman cast his net into the water.',
    'Dolphin': 'We saw a dolphin jumping out of the water.',
    'Whale': 'Whale watching is a popular tourist activity here.',
    'Shark': 'A shark was spotted near the beach yesterday.',
    'Island': 'They live on a small island in the Pacific.',
    'Archipelago': 'Indonesia is the largest archipelago in the world.',
    'Beach vacation': 'We are planning a relaxing beach vacation for the summer.',
    'Seaside resort': 'We stayed at a luxury seaside resort for our honeymoon.',
    'Sunbathe': 'She likes to sunbathe on the beach in the morning.',
    'Swim': 'I swim in the ocean every day.',
    'Snorkeling': 'Snorkeling in the clear water was amazing.',
    'Scuba diving': 'He took scuba diving lessons before his trip to Hawaii.',
    'Surfing': 'Surfing is very popular on this coast.',
    'Beach volleyball': 'We played a game of beach volleyball with some friends.',
    'Beach umbrella': 'We set up a beach umbrella to get some shade.',
    'Sandcastle': 'The children built a huge sandcastle on the beach.',
    'Lifeguard': 'The lifeguard warned everyone about the strong currents.',
    'Suncream': 'Don\'t forget to apply suncream before going out in the sun.',
    'Flip-flops': 'I only wear flip-flops when I go to the beach.',
    'Beach towel': 'She laid her beach towel on the sand and lay down.',
    'Seashell': 'She collected a beautiful seashell by the shore.',
    'Boat tour': 'We took a boat tour to see the coastal cliffs.',
    'Yacht charter': 'They booked a yacht charter for their family vacation.',
    'Beach party': 'There was a huge beach party with music and dancing.',
    'Fishing trip': 'My father went on a fishing trip with his friends.',
    'Jet ski': 'Riding a jet ski is a lot of fun.',
    'Kayaking': 'We went kayaking along the rugged coastline.',
    'Windsurfing': 'The windy weather was perfect for windsurfing.',
    'Parasailing': 'Parasailing gave us a great aerial view of the ocean.',
    'Seafood': 'This restaurant serves the best seafood in town.',
    'Coastal path': 'We walked along the coastal path for an hour.',
    'Sunset cruise': 'The sunset cruise was incredibly romantic.',
    'Salmon': 'Grilled salmon is my favorite dish.',
    'Tuna': 'I had a tuna sandwich for lunch.',
    'Mackerel': 'Mackerel is rich in omega-3 fatty acids.',
    'Sardine': 'He bought a can of sardines for the camping trip.',
    'Cod': 'Fish and chips are traditionally made with cod.',
    'Herring': 'Pickled herring is a traditional dish in many European countries.',
    'Anchovy': 'Some people love anchovy on their pizza.',
    'Haddock': 'Haddock is a popular fish for smoking.',
    'Halibut': 'We ordered pan-seared halibut for dinner.',
    'Snapper': 'Red snapper is known for its sweet, nutty flavor.',
    'Grouper': 'The chef prepared a delicious baked grouper.',
    'Swordfish': 'Swordfish steaks are excellent when grilled.',
    'Marlin': 'The marlin is a fast and powerful game fish.',
    'Barracuda': 'A barracuda is a fierce predatory fish.',
    'Bass': 'He caught a large sea bass this morning.',
    'Flounder': 'Flounder is a flatfish found at the bottom of the ocean.',
    'Sole': 'Lemon sole is very popular in French cuisine.',
    'Monkfish': 'Monkfish has a firm texture similar to lobster.',
    'Sea bass': 'We enjoyed a meal of roasted sea bass.',
    'Kingfish': 'Kingfish is a popular target for sport fishers.',
    'Whiting': 'Whiting is a versatile fish used in many recipes.',
    'Pollock': 'Pollock is often used to make imitation crab meat.',
    'Bluefish': 'Bluefish have very sharp teeth.',
    'Yellowtail': 'Yellowtail is commonly served as sushi or sashimi.',
    'Amberjack': 'Amberjack is known for its fighting ability when hooked.',
    'Redfish': 'Blackened redfish is a famous Louisiana dish.',
    'Tilapia': 'Tilapia is a mild-flavored fish that is easy to farm.',
    'Catfish': 'Fried catfish is a Southern classic.',
    'Eel': 'Grilled eel, or unagi, is delicious in Japanese cuisine.',
    'Albatross': 'An albatross can fly for thousands of miles without resting.',
    'Pelican': 'The pelican scooped up a fish in its large pouch.',
    'Puffin': 'The puffin has a brightly colored beak during the breeding season.',
    'Tern': 'The arctic tern migrates from pole to pole every year.',
    'Gannet': 'A gannet dives into the water at high speed to catch fish.',
    'Shearwater': 'The shearwater gracefully glided over the ocean waves.',
    'Skua': 'The skua is known for stealing food from other seabirds.',
    'Petrel': 'The storm petrel is a small seabird that flutters over the water.',
    'Cormorant': 'The cormorant stood on a rock with its wings spread to dry.',
    'Frigatebird': 'The frigatebird has a distinctive red throat pouch.',
    'Oystercatcher': 'The oystercatcher uses its strong beak to open shells.',
    'Plover': 'The plover ran quickly along the edge of the water.',
    'Kingfisher': 'The kingfisher dived into the river to catch a small fish.',
    'Sandpiper': 'We watched a flock of sandpipers running on the beach.',
    'Seabird': 'A seabird soared gracefully above the cliffs.',
    'Heron': 'A great blue heron stood motionless in the shallow water.',
    'Egret': 'The snowy egret has beautiful white plumage.',
    'Osprey': 'An osprey caught a large fish in its talons.',
    'Tropicbird': 'The tropicbird is recognizable by its long tail feathers.',
    'Wader': 'Waders often have long legs for walking in shallow water.',
    'Gull': 'A gull flew down and snatched a piece of bread.',
    'Razorbill': 'The razorbill breeds in colonies on rocky coastal cliffs.',
    'Guillemot': 'The guillemot lays its pear-shaped eggs on bare rock ledges.',
    'Murre': 'The common murre is a seabird that looks similar to a penguin.',
    'Shag': 'The European shag is slightly smaller than a cormorant.',
    'Fulmar': 'The northern fulmar is a common seabird in the North Atlantic.',
    'Clam': 'We dug for clams in the wet sand during low tide.',
    'Mussel': 'She ordered a bowl of mussels cooked in white wine.',
    'Oyster': 'Fresh oysters are often served on the half shell with lemon.',
    'Scallop': 'Seared scallops make an elegant appetizer.',
    'Snail': 'A sea snail was moving slowly across the rock.',
    'Barnacle': 'The bottom of the boat was covered in barnacles.',
    'Conch': 'Blowing into a conch shell produces a loud, resonant sound.',
    'Abalone': 'The iridescent inside of an abalone shell is used in jewelry.',
    'Nautilus': 'The nautilus has a beautiful spiral shell.',
    'Lobster': 'We had a fancy dinner with Maine lobster.',
    'Crab': 'The crab scurried sideways across the sand.',
    'Shrimp': 'She added some grilled shrimp to her salad.',
    'Starfish': 'We found a bright orange starfish in the tide pool.',
    'Sea urchin': 'Be careful not to step on a sea urchin.',
    'Sea snail': 'Many sea snail species have beautifully patterned shells.',
    'Mollusk': 'An octopus is a highly intelligent marine mollusk.',
    'Slug': 'A sea slug is known for its striking colors and patterns.',
    'Octopus': 'The octopus changed its color to blend in with the rocks.',
    'Squid': 'Giant squid live deep in the ocean.',
    'Cuttlefish': 'Cuttlefish can rapidly alter their skin color and pattern.',
    'Jellyfish': 'I got stung by a jellyfish while swimming.',
    'Turtle': 'We saw a sea turtle gracefully swimming near the reef.',
    'Seal': 'A seal was resting on a piece of floating ice.',
    'Walrus': 'The walrus uses its long tusks to pull itself onto the ice.',
    'Manatee': 'The manatee is a gentle, slow-moving marine mammal.',
    'Seahorse': 'The seahorse anchored itself to a piece of seagrass with its tail.',
    'Angelfish': 'The angelfish is popular in many saltwater aquariums.',
    'Clownfish': 'The clownfish lives safely among the tentacles of a sea anemone.',
    'Sponge': 'A sea sponge filters water to obtain its food.',
    'Sea anemone': 'A sea anemone looks like an underwater flower.',
    'Pacific Ocean': 'The Pacific Ocean separates Asia and the Americas.',
    'Atlantic Ocean': 'They flew across the Atlantic Ocean from London to New York.',
    'Indian Ocean': 'The Maldives are located in the Indian Ocean.',
    'Arctic Ocean': 'The Arctic Ocean is covered by sea ice for most of the year.',
    'Southern Ocean': 'The Southern Ocean surrounds the continent of Antarctica.',
    'Mediterranean Sea': 'The Mediterranean Sea is bordered by Southern Europe and North Africa.',
    'Caribbean Sea': 'We took a cruise through the Caribbean Sea.',
    'South China Sea': 'The South China Sea is a marginal sea of the Western Pacific.',
    'Baltic Sea': 'The Baltic Sea is located in Northern Europe.',
    'Black Sea': 'The Black Sea connects to the Mediterranean via the Bosporus.',
    'Red Sea': 'The Red Sea is known for its spectacular diving sites.',
    'Arabian Sea': 'The Arabian Sea is a region of the northern Indian Ocean.',
    'Caspian Sea': 'The Caspian Sea is the world\'s largest inland body of water.',
    'Andaman Sea': 'The Andaman Sea is located in the northeastern Indian Ocean.',
    'Tasman Sea': 'The Tasman Sea lies between Australia and New Zealand.',
    'Coral Sea': 'The Great Barrier Reef is located in the Coral Sea.',
    'Tyrrhenian Sea': 'The Tyrrhenian Sea is part of the Mediterranean Sea off the western coast of Italy.',
    'Adriatic Sea': 'The Adriatic Sea separates the Italian Peninsula from the Balkan Peninsula.',
    'Swimsuit': 'Don\'t forget to pack your swimsuit for the trip.',
    'Sunscreen': 'Apply sunscreen generously to protect your skin.',
    'Sunglasses': 'She wore sunglasses to protect her eyes from the glare.',
    'Hat': 'He wore a wide-brimmed hat to keep the sun off his face.',
    'Towel': 'I need a dry towel after coming out of the water.',
    'Beach bag': 'She stuffed all her things into a large beach bag.',
    'Beach chair': 'He sat back in his beach chair and read a book.',
    'Cooler': 'We brought a cooler full of cold drinks to the beach.',
    'Snorkel': 'You breathe through a snorkel when swimming near the surface.',
    'Mask': 'The diving mask allowed him to see clearly underwater.',
    'Fins': 'Wearing fins helps you swim much faster.',
    'Beach mat': 'She unrolled her beach mat on the hot sand.',
    'Waterproof bag': 'Keep your phone safe in a waterproof bag.',
    'Beach ball': 'The kids tossed a beach ball back and forth.',
    'Sandals': 'Sandals are the best footwear for a day at the beach.',
    'Beach tent': 'A beach tent provides excellent shade for babies.',
    'Water shoes': 'Water shoes protect your feet from sharp rocks.',
    'A drop in the ocean': 'His contribution was just a drop in the ocean compared to what was needed.',
    'To weather the storm': 'The company managed to weather the storm during the economic crisis.',
    'To be all at sea': 'When I started my new job, I was all at sea.',
    'Plain sailing': 'Once we fixed the bug, the rest of the project was plain sailing.',
    'To be a drop in the bucket': 'The money raised is just a drop in the bucket.',
    'To make waves': 'She doesn\'t like to make waves at the office.',
    'To sail through something': 'He sailed through his final exams without any trouble.',
    'To be in deep water': 'If he misses this deadline, he will be in deep water.',
    'To be like a fish out of water': 'At the fancy gala, I felt like a fish out of water.',
    'To go with the flow': 'Sometimes you just have to relax and go with the flow.',
    'Sink or swim': 'It’s his first week on the job, so it’s sink or swim.',
    'To be on the crest of a wave': 'The band is currently on the crest of a wave after their hit song.',
    'To be a sea change': 'There has been a sea change in public attitudes toward recycling.',
    'To miss the boat': 'If you don\'t buy the tickets now, you\'ll miss the boat.',
    'To ride the wave': 'The business is trying to ride the wave of the new technology trend.',
    'To be like water off a ducks back': 'Criticism is like water off a duck\'s back to him.',
    'To test the waters': 'Let’s test the waters with a small pilot program before launching.',
    'To have bigger fish to fry': 'I couldn\'t attend the meeting because I had bigger fish to fry.',
    'To be like a sinking ship': 'Investors are abandoning the company like a sinking ship.',
    'To be a sea of faces': 'I looked out into the audience and saw a sea of faces.',
    'To be a wave of enthusiasm': 'A wave of enthusiasm swept part the crowd.',
    'To be in hot water': 'He got in hot water for being late to work again.',
    'To be out of the blue': 'The job offer came completely out of the blue.',
    'To swim against the tide': 'It can be exhausting to always swim against the tide.',
    'To be all washed up': 'Many thought his acting career was all washed up.',
    'To be a fish in troubled waters': 'He has been fishing in troubled waters by interfering in their argument.',
    'To be in smooth waters': 'After months of struggle, the business is finally in smooth waters.',
    'To be in uncharted waters': 'With this new AI technology, we are in uncharted waters.',
    'To pour oil on troubled waters': 'He stepped in to pour oil on troubled waters during the heated debate.',
    'To be a sea of change': 'The internet brought about a sea of change in how we communicate.'
}

# Mapping for Part of Speech
pos_mapping = {
    'N': 'NOUN',
    'V': 'VERB',
    'Adj': 'ADJECTIVE',
    'Phr': 'Phrase',
    'Adv': 'ADVERB',
    'Prep': 'PREPOSITION',
    'Conj': 'CONJUNCTION',
    'Pro': 'PRONOUN'
}

df = pd.read_excel('vocab_sea.xlsx')

# 1. Update the Example column
def get_example(term):
    # Try exact match
    if term in examples:
        return examples[term]
    
    # Try with apostrophe fix
    fixed = term.replace("’", "'").replace("'", "")
    if fixed in examples:
        return examples[fixed]
        
    return ''

df['Example'] = df['Term'].apply(lambda x: get_example(str(x).strip()))

# 2. Update the PartOfSpeech column
def map_pos(pos):
    pos = str(pos).strip()
    return pos_mapping.get(pos, pos)  # Return mapped value, or original if not found

df['PartOfSpeech'] = df['PartOfSpeech'].apply(map_pos)

# To avoid PermissionError if the file is open, we save to a new file
try:
    df.to_excel('vocab_sea.xlsx', index=False)
    print("Saved to vocab_sea.xlsx")
except PermissionError:
    df.to_excel('vocab_sea_updated.xlsx', index=False)
    print("Saved to vocab_sea_updated.xlsx because vocab_sea.xlsx was open.")
except Exception as e:
    print(f"Error: {e}")
