import pandas as pd
import os

# Combine all lists: 
# Total: 68 (img1) + 72 (img2) + 60 (img3) = 200 words exactly!

data = [
    # Image 1
    ["accelerate", "/əkˈseləreɪt/", "VERB", "speed up, quicken, expedite", "decelerate, slow down", "tăng tốc, thúc đẩy", "The company plans to accelerate its expansion into new markets."],
    ["accumulate", "/əˈkjuːmjəleɪt/", "VERB", "amass, gather, collect", "disperse, scatter", "tích lũy", "Dust tends to accumulate on top of the cupboards."],
    ["acknowledge", "/əkˈnɒlɪdʒ/", "VERB", "admit, recognize, concede", "deny, reject", "thừa nhận, công nhận", "He refused to acknowledge that he had made a mistake."],
    ["advocate", "/ˈædvəkeɪt/", "VERB", "support, promote, champion", "oppose, condemn", "ủng hộ, chủ trương", "Environmentalists advocate the use of renewable energy."],
    ["allocate", "/ˈæləkeɪt/", "VERB", "assign, distribute, allot", "withhold, keep", "phân bổ", "The government will allocate more funds to education."],
    ["alleviate", "/əˈliːvieɪt/", "VERB", "ease, relieve, mitigate", "aggravate, worsen", "làm giảm, xoa dịu", "The doctor prescribed medication to alleviate her pain."],
    ["alter", "/ˈɔːltər/", "VERB", "change, modify, adjust", "maintain, preserve", "thay đổi", "We may need to alter our plans due to the weather."],
    ["ambiguous", "/æmˈbɪɡjuəs/", "ADJECTIVE", "unclear, vague, obscure", "clear, explicit", "mơ hồ", "The phrasing of the law is highly ambiguous."],
    ["anticipate", "/ænˈtɪsɪpeɪt/", "VERB", "expect, foresee, predict", "doubt, be surprised", "dự đoán, lường trước", "We anticipate a significant increase in sales this quarter."],
    ["apparent", "/əˈpærənt/", "ADJECTIVE", "obvious, clear, evident", "hidden, obscure", "rõ ràng, có vẻ", "It became apparent that the project would fail."],
    ["arbitrary", "/ˈɑːrbɪtrəri/", "ADJECTIVE", "random, subjective, capricious", "rational, logical", "tùy ý, thiếu cơ sở rõ ràng", "The decision seemed entirely arbitrary."],
    ["arise", "/əˈraɪz/", "VERB", "emerge, occur, happen", "disappear, resolve", "phát sinh", "New problems will inevitably arise during the project."],
    ["articulate", "/ɑːrˈtɪkjuleɪt/", "VERB", "express, state, communicate", "mumble, hesitate", "diễn đạt rõ ràng", "She struggled to articulate her feelings."],
    ["ascribe", "/əˈskraɪb/", "VERB", "attribute, assign, credit", "detach, disconnect", "quy cho", "They ascribe his success to hard work and dedication."],
    ["assume", "/əˈsuːm/", "VERB", "presume, suppose, guess", "know, prove", "giả định", "It is safe to assume that the meeting will be delayed."],
    ["attribute", "/əˈtrɪbjuːt/", "VERB", "ascribe, assign, credit", "disconnect", "quy cho", "She attributes her success to her parents' support."],
    ["bias", "/ˈbaɪəs/", "NOUN", "prejudice, partiality, favoritism", "fairness, impartiality", "thiên kiến", "The media was accused of political bias."],
    ["coherent", "/koʊˈhɪrənt/", "ADJECTIVE", "logical, consistent, organized", "disjointed, confused", "mạch lạc, nhất quán", "He was too upset to give a coherent account of the event."],
    ["compelling", "/kəmˈpelɪŋ/", "ADJECTIVE", "convincing, persuasive, irresistible", "weak, unconvincing", "thuyết phục", "The lawyer presented a compelling argument."],
    ["comprehensive", "/ˌkɑːmprɪˈhensɪv/", "ADJECTIVE", "thorough, complete, inclusive", "partial, limited", "toàn diện", "The report provides a comprehensive overview of the issue."],
    ["comprise", "/kəmˈpraɪz/", "VERB", "consist of, contain, include", "exclude, lack", "bao gồm", "The committee is comprised of representatives from both sides."],
    ["concede", "/kənˈsiːd/", "VERB", "admit, yield, surrender", "deny, dispute", "thừa nhận", "The company finally conceded that their product was flawed."],
    ["constrain", "/kənˈstreɪn/", "VERB", "restrict, limit, force", "free, liberate", "hạn chế", "Our research was constrained by a lack of funding."],
    ["constraint", "/kənˈstreɪnt/", "NOUN", "restriction, limitation, restraint", "freedom, liberty", "sự hạn chế", "Financial constraints prevented them from expanding the business."],
    ["contend", "/kənˈtend/", "VERB", "argue, assert, claim", "agree, comply", "lập luận, cho rằng", "The defense attorney contends that his client is innocent."],
    ["contradict", "/ˌkɑːntrəˈdɪkt/", "VERB", "oppose, deny, counter", "agree, confirm", "mâu thuẫn với", "The witness's testimony contradicts the defendant's story."],
    ["corroborate", "/kəˈrɑːbəreɪt/", "VERB", "confirm, verify, support", "contradict, refute", "xác nhận bằng bằng chứng", "The evidence corroborates the victim's account of the attack."],
    ["credible", "/ˈkredəbl/", "ADJECTIVE", "believable, reliable, trustworthy", "unbelievable, unreliable", "đáng tin cậy", "We need to find a credible witness to testify in court."],
    ["crucial", "/ˈkruːʃl/", "ADJECTIVE", "vital, essential, critical", "trivial, insignificant", "then chốt", "Teamwork is crucial to the success of this project."],
    ["cumulative", "/ˈkjuːmjələtɪv/", "ADJECTIVE", "accumulative, aggregate, collective", "subtractive, decreasing", "mang tính tích lũy", "The cumulative effect of the changes was significant."],
    ["derive", "/dɪˈraɪv/", "VERB", "obtain, get, extract", "give, lose", "bắt nguồn, thu được", "Many English words derive from Latin."],
    ["deteriorate", "/dɪˈtɪriəreɪt/", "VERB", "worsen, decline, degrade", "improve, ameliorate", "xấu đi", "The patient's condition began to deteriorate rapidly."],
    ["detrimental", "/ˌdetrɪˈmentl/", "ADJECTIVE", "harmful, damaging, adverse", "beneficial, helpful", "có hại", "Smoking is detrimental to your health."],
    ["devise", "/dɪˈvaɪz/", "VERB", "invent, create, formulate", "destroy, ruin", "nghĩ ra, thiết kế", "They have devised a new method for recycling plastic."],
    ["propagate", "/ˈprɑːpəɡeɪt/", "VERB", "spread, disseminate, reproduce", "conceal, suppress", "lan truyền, nhân giống", "The internet is a powerful tool to propagate information."],
    ["prone", "/proʊn/", "ADJECTIVE", "susceptible, inclined, vulnerable", "immune, resistant", "dễ có xu hướng, dễ bị", "He is prone to making mistakes when under pressure."],
    ["provisional", "/prəˈvɪʒənl/", "ADJECTIVE", "temporary, tentative, conditional", "permanent, definite", "tạm thời, sơ bộ", "The government formed a provisional administration."],
    ["stark", "/stɑːrk/", "ADJECTIVE", "sharp, clear, sheer", "subtle, blurred", "rõ rệt, tương phản mạnh", "There is a stark contrast between the two neighborhoods."],
    ["reconcile", "/ˈrekənsaɪl/", "VERB", "harmonize, resolve, settle", "alienate, estrange", "dung hòa", "It is difficult to reconcile his words with his actions."],
    ["redundant", "/rɪˈdʌndənt/", "ADJECTIVE", "unnecessary, superfluous, extra", "essential, necessary", "dư thừa", "The factory closed down, making hundreds of workers redundant."],
    ["reinforce", "/ˌriːɪnˈfɔːrs/", "VERB", "strengthen, support, bolster", "weaken, undermine", "củng cố", "The building was reinforced with steel beams."],
    ["replicate", "/ˈreplɪkeɪt/", "VERB", "duplicate, copy, reproduce", "originate, destroy", "tái tạo, lặp lại", "The scientists were unable to replicate the results of the experiment."],
    ["residual", "/rɪˈzɪdʒuəl/", "ADJECTIVE/NOUN", "remaining, leftover, lingering", "core, base", "còn lại, phần dư", "There was a residual amount of chemical left in the tube."],
    ["resilient", "/rɪˈzɪliənt/", "ADJECTIVE", "tough, flexible, adaptable", "fragile, vulnerable", "có khả năng phục hồi", "Children are often much more resilient than adults."],
    ["restrict", "/rɪˈstrɪkt/", "VERB", "limit, confine, regulate", "expand, free", "hạn chế", "Access to the laboratory is restricted to authorized personnel."],
    ["rigorous", "/ˈrɪɡərəs/", "ADJECTIVE", "strict, thorough, severe", "lax, lenient", "nghiêm ngặt", "The students must pass a rigorous examination to graduate."],
    ["robust", "/roʊˈbʌst/", "ADJECTIVE", "strong, sturdy, vigorous", "weak, fragile", "vững chắc", "We need a robust system that can handle large amounts of data."],
    ["salient", "/ˈseɪliənt/", "ADJECTIVE", "prominent, outstanding, noticeable", "minor, insignificant", "nổi bật, đáng chú ý", "She pointed out the salient features of the new design."],
    ["scrutiny", "/ˈskruːtəni/", "NOUN", "inspection, examination, analysis", "glance, ignore", "sự xem xét kỹ lưỡng", "The company's financial records are under close scrutiny."],
    ["sceptical", "/ˈskeptɪkl/", "ADJECTIVE", "doubtful, cynical, dubious", "convinced, credulous", "hoài nghi", "I am highly sceptical about his promises."],
    ["simultaneous", "/ˌsaɪmlˈteɪniəs/", "ADJECTIVE", "concurrent, coinciding, synchronous", "sequential, consecutive", "đồng thời", "There were simultaneous protests in several cities."],
    ["sporadic", "/spəˈrædɪk/", "ADJECTIVE", "occasional, irregular, intermittent", "continuous, frequent", "rải rác, không thường xuyên", "There were reports of sporadic fighting in the region."],
    ["substantiate", "/səbˈstænʃieɪt/", "VERB", "prove, verify, confirm", "disprove, contradict", "chứng minh bằng bằng chứng", "They have not been able to substantiate their claims."],
    ["substantial", "/səbˈstænʃl/", "ADJECTIVE", "considerable, significant, large", "slight, minor", "đáng kể, lớn", "There has been a substantial increase in the cost of living."],
    ["subsequent", "/ˈsʌbsɪkwənt/", "ADJECTIVE", "following, succeeding, later", "previous, prior", "tiếp theo", "Those explosions must have been subsequent to our departure."],
    ["susceptible", "/səˈseptəbl/", "ADJECTIVE", "vulnerable, prone, sensitive", "immune, resistant", "dễ bị ảnh hưởng", "Older people are more susceptible to infections."],
    ["sustain", "/səˈsteɪn/", "VERB", "maintain, support, prolong", "abandon, halt", "duy trì", "He was unable to sustain his interest in the project."],
    ["tangible", "/ˈtændʒəbl/", "ADJECTIVE", "concrete, physical, palpable", "intangible, abstract", "rõ rệt, hữu hình", "We need tangible evidence to proceed with the investigation."],
    ["tentative", "/ˈtentətɪv/", "ADJECTIVE", "provisional, unconfirmed, hesitant", "definite, certain", "tạm thời, chưa chắc chắn", "They have reached a tentative agreement."],
    ["threshold", "/ˈθreʃhoʊld/", "NOUN", "brink, verge, start", "end, conclusion", "ngưỡng", "She has a low threshold for pain."],
    ["trajectory", "/trəˈdʒektəri/", "NOUN", "path, course, route", "deviation", "quỹ đạo, xu hướng phát triển", "The missile's trajectory was tracked by radar."],
    ["transient", "/ˈtrænziənt/", "ADJECTIVE", "temporary, fleeting, brief", "permanent, lasting", "tạm thời", "The city has a large transient population."],
    ["trigger", "/ˈtrɪɡər/", "VERB/NOUN", "provoke, initiate, spark", "prevent, halt", "gây ra, tác nhân kích hoạt", "Certain foods can trigger his allergies."],
    ["undermine", "/ˌʌndərˈmaɪn/", "VERB", "weaken, compromise, sabotage", "strengthen, support", "làm suy yếu", "Their constant criticism undermined his confidence."],
    ["underpin", "/ˌʌndərˈpɪn/", "VERB", "support, base, fortify", "weaken, undermine", "làm nền tảng", "These arguments underpin the proposed changes to the law."],
    ["undergo", "/ˌʌndərˈɡoʊ/", "VERB", "experience, endure, go through", "avoid, escape", "trải qua", "The company is undergoing a major restructuring."],
    ["unprecedented", "/ʌnˈpresɪdentɪd/", "ADJECTIVE", "unparalleled, unmatched, extraordinary", "common, normal", "chưa từng có tiền lệ", "We are facing an unprecedented global crisis."],
    ["validate", "/ˈvælɪdeɪt/", "VERB", "confirm, authenticate, prove", "invalidate, reject", "xác nhận tính hợp lệ", "The data must be validated before it can be used."],
    
    # Image 2
    ["diminish", "/dɪˈmɪnɪʃ/", "VERB", "reduce, decrease, lessen", "increase, grow", "suy giảm", "The pain will gradually diminish over time."],
    ["discrepancy", "/dɪˈskrepənsi/", "NOUN", "inconsistency, difference, disparity", "agreement, similarity", "sự không nhất quán", "There is a discrepancy between the two accounts of the event."],
    ["disseminate", "/dɪˈsemɪneɪt/", "VERB", "spread, broadcast, circulate", "conceal, hide", "phổ biến, truyền bá", "The agency aims to disseminate information about the disease."],
    ["distinguish", "/dɪˈstɪŋɡwɪʃ/", "VERB", "differentiate, separate, discriminate", "confuse, mix up", "phân biệt", "It is difficult to distinguish between the two twins."],
    ["distort", "/dɪˈstɔːrt/", "VERB", "twist, warp, misrepresent", "straighten, clarify", "làm sai lệch", "The media was accused of distorting the facts."],
    ["disrupt", "/dɪsˈrʌpt/", "VERB", "interrupt, disturb, interfere", "organize, arrange", "làm gián đoạn", "The storm severely disrupted the train services."],
    ["diverse", "/daɪˈvɜːrs/", "ADJECTIVE", "various, varied, mixed", "similar, identical", "đa dạng", "New York is a culturally diverse city."],
    ["drastic", "/ˈdræstɪk/", "ADJECTIVE", "extreme, severe, radical", "mild, moderate", "mạnh, quyết liệt", "The government took drastic measures to reduce pollution."],
    ["elaborate", "/ɪˈlæbərət/", "ADJECTIVE", "detailed, complicated, complex", "simple, plain", "phức tạp, công phu", "They prepared an elaborate feast for the guests."],
    ["elicit", "/ɪˈlɪsɪt/", "VERB", "obtain, extract, evoke", "suppress, hide", "gợi ra, thu được", "The questionnaire was designed to elicit information about their habits."],
    ["eliminate", "/ɪˈlɪmɪneɪt/", "VERB", "remove, get rid of, eradicate", "add, include", "loại bỏ", "We must eliminate the risk of infection."],
    ["empirical", "/ɪmˈpɪrɪkl/", "ADJECTIVE", "observed, practical, experimental", "theoretical, hypothetical", "dựa trên thực nghiệm", "There is no empirical evidence to support his theory."],
    ["encompass", "/ɪnˈkʌmpəs/", "VERB", "include, cover, embrace", "exclude, omit", "bao gồm", "The job encompasses a wide range of responsibilities."],
    ["enhance", "/ɪnˈhæns/", "VERB", "improve, increase, boost", "diminish, reduce", "nâng cao", "Adding spices will enhance the flavor of the dish."],
    ["entail", "/ɪnˈteɪl/", "VERB", "involve, require, demand", "exclude, omit", "kéo theo, đòi hỏi", "The project will entail a lot of hard work."],
    ["equivalent", "/ɪˈkwɪvələnt/", "ADJECTIVE/NOUN", "equal, identical, comparable", "different, dissimilar", "tương đương", "The two systems are roughly equivalent in performance."],
    ["ubiquitous", "/juːˈbɪkwɪtəs/", "ADJECTIVE", "omnipresent, everywhere, universal", "rare, scarce", "có mặt khắp nơi", "Mobile phones have become ubiquitous in modern society."],
    ["unequivocal", "/ˌʌnɪˈkwɪvəkl/", "ADJECTIVE", "clear, unambiguous, unmistakable", "ambiguous, vague", "rõ ràng, không mơ hồ", "The answer was an unequivocal 'no'."],
    ["proponent", "/prəˈpoʊnənt/", "NOUN", "supporter, advocate, promoter", "opponent, critic", "người ủng hộ", "She is a strong proponent of women's rights."],
    ["eradicate", "/ɪˈrædɪkeɪt/", "VERB", "eliminate, wipe out, destroy", "establish, create", "xóa bỏ hoàn toàn", "The disease has now been completely eradicated."],
    ["exacerbate", "/ɪɡˈzæsərbeɪt/", "VERB", "worsen, aggravate, inflame", "alleviate, ease", "làm trầm trọng thêm", "His comments only exacerbated the situation."],
    ["exceed", "/ɪkˈsiːd/", "VERB", "surpass, top, outdo", "fall short, fail", "vượt quá", "The cost will not exceed $50."],
    ["exclude", "/ɪkˈskluːd/", "VERB", "keep out, omit, rule out", "include, admit", "loại trừ", "We cannot exclude the possibility of an error."],
    ["explicit", "/ɪkˈsplɪsɪt/", "ADJECTIVE", "clear, direct, specific", "implicit, vague", "rõ ràng, trực tiếp", "He gave me explicit instructions on what to do."],
    ["extrapolate", "/ɪkˈstræpəleɪt/", "VERB", "deduce, project, predict", "doubt, guess", "ngoại suy", "It is difficult to extrapolate from these limited results."],
    ["facilitate", "/fəˈsɪlɪteɪt/", "VERB", "ease, aid, assist", "hinder, impede", "tạo điều kiện", "The new software will facilitate the learning process."],
    ["feasible", "/ˈfiːzəbl/", "ADJECTIVE", "practicable, viable, possible", "impossible, impractical", "khả thi", "It's just not feasible to manage the business alone."],
    ["formulate", "/ˈfɔːrmjuleɪt/", "VERB", "develop, devise, invent", "destroy, ruin", "xây dựng, hình thành", "They formulated a plan to tackle the problem."],
    ["foster", "/ˈfɔːstər/", "VERB", "encourage, promote, cultivate", "neglect, suppress", "thúc đẩy, nuôi dưỡng", "The school aims to foster a love of reading."],
    ["fundamental", "/ˌfʌndəˈmentl/", "ADJECTIVE", "basic, essential, primary", "secondary, trivial", "nền tảng", "There is a fundamental difference between the two approaches."],
    ["harness", "/ˈhɑːrnɪs/", "VERB", "utilize, exploit, use", "waste, ignore", "khai thác, tận dụng", "We must harness the power of the sun."],
    ["hypothesis", "/haɪˈpɑːθəsɪs/", "NOUN", "theory, assumption, proposition", "fact, proof", "giả thuyết", "Our findings support the initial hypothesis."],
    ["imply", "/ɪmˈplaɪ/", "VERB", "suggest, hint, insinuate", "state directly, explicate", "ngụ ý", "Are you implying that I am lying?"],
    ["impede", "/ɪmˈpiːd/", "VERB", "hinder, obstruct, delay", "facilitate, assist", "cản trở", "The bad weather impeded our progress."],
    ["implicit", "/ɪmˈplɪsɪt/", "ADJECTIVE", "implied, unspoken, underlying", "explicit, stated", "ngầm, không nói trực tiếp", "There was an implicit agreement between them."],
    ["incentive", "/ɪnˈsentɪv/", "NOUN", "motivation, encouragement, stimulus", "deterrent, discouragement", "động lực, sự khuyến khích", "The bonus was an incentive for employees to work harder."],
    ["viable", "/ˈvaɪəbl/", "ADJECTIVE", "feasible, workable, practical", "impossible, unworkable", "khả thi", "We need to find a commercially viable solution."],
    ["vulnerability", "/ˌvʌlnərəˈbɪləti/", "NOUN", "weakness, susceptibility, defenselessness", "strength, resilience", "tính dễ bị tổn thương", "The system's vulnerability to hackers is a major concern."],
    ["warrant", "/ˈwɔːrənt/", "VERB", "justify, vindicate, deserve", "invalidate, forbid", "biện minh, cho phép kết luận", "The situation does not warrant such extreme measures."],
    ["amplify", "/ˈæmplɪfaɪ/", "VERB", "magnify, intensify, boost", "reduce, muffle", "khuếch đại", "The microphone amplified his voice across the room."],
    ["autonomous", "/ɔːˈtɑːnəməs/", "ADJECTIVE", "independent, self-governing, self-ruling", "dependent, subordinate", "tự chủ", "The province sought to become an autonomous region."],
    ["bolster", "/ˈboʊlstər/", "VERB", "strengthen, support, reinforce", "undermine, weaken", "củng cố, hỗ trợ", "They needed to bolster their defense against the attack."],
    ["causal", "/ˈkɔːzl/", "ADJECTIVE", "related, linked, sequential", "unrelated", "thuộc quan hệ nhân quả", "There is a causal link between smoking and lung cancer."],
    ["coincide", "/ˌkoʊɪnˈsaɪd/", "VERB", "clash, occur simultaneously, overlap", "differ, diverge", "xảy ra đồng thời, trùng hợp", "My birthday coincides with a public holiday."],
    ["compensate", "/ˈkɑːmpenseɪt/", "VERB", "recompense, make up for, reimburse", "deprive, penalize", "bù đắp", "Nothing can compensate for the loss of a loved one."],
    ["confer", "/kənˈfɜːr/", "VERB", "grant, bestow, give", "withhold, take", "mang lại, trao", "An honorary degree was conferred on him by the university."],
    ["consecutive", "/kənˈsekjətɪv/", "ADJECTIVE", "successive, sequential, continuous", "interrupted, non-sequential", "liên tiếp", "It rained for five consecutive days."],
    ["constitute", "/ˈkɑːnstɪtuːt/", "VERB", "make up, form, compose", "destroy, dismantle", "cấu thành, chiếm", "Women constitute the majority of the workforce in this sector."],
    ["counteract", "/ˌkaʊntərˈækt/", "VERB", "offset, neutralize, negate", "assist, encourage", "chống lại, làm giảm tác động", "We need to counteract the negative effects of the policy."],
    ["deviate", "/ˈdiːvieɪt/", "VERB", "diverge, stray, drift", "conform, stay", "lệch khỏi", "He never deviated from his original plan."],
    ["diffuse", "/dɪˈfjuːz/", "VERB/ADJECTIVE", "spread, scatter, disperse", "concentrate, focus", "khuếch tán, lan rộng", "The gas quickly diffused throughout the room."],
    ["discrete", "/dɪˈskriːt/", "ADJECTIVE", "separate, distinct, individual", "continuous, attached", "riêng biệt", "The data is divided into several discrete categories."],
    ["disproportionate", "/ˌdɪsprəˈpɔːrʃənət/", "ADJECTIVE", "unequal, uneven, unbalanced", "proportionate, equal", "không cân xứng", "A disproportionate amount of the budget was spent on administration."],
    ["diverge", "/daɪˈvɜːrdʒ/", "VERB", "separate, branch off, differ", "converge, merge", "khác nhau, phân kỳ", "Our views on the subject diverge significantly."],
    ["enduring", "/ɪnˈdʊrɪŋ/", "ADJECTIVE", "lasting, permanent, abiding", "temporary, fleeting", "lâu dài", "He has an enduring love for classical music."],
    ["finite", "/ˈfaɪnaɪt/", "ADJECTIVE", "limited, bounded, restricted", "infinite, endless", "hữu hạn", "The earth has a finite supply of natural resources."],
    ["impartial", "/ɪmˈpɑːrʃl/", "ADJECTIVE", "unbiased, neutral, fair", "biased, prejudiced", "không thiên vị", "A judge must remain impartial at all times."],
    ["precarious", "/prɪˈkeriəs/", "ADJECTIVE", "insecure, uncertain, risky", "secure, safe", "bấp bênh", "She is in a precarious financial situation."],
    ["homogeneous", "/ˌhoʊməˈdʒiːniəs/", "ADJECTIVE", "uniform, similar, identical", "heterogeneous, varied", "đồng nhất", "The population of the village is remarkably homogeneous."],
    ["heterogeneous", "/ˌhetərəˈdʒiːniəs/", "ADJECTIVE", "diverse, varied, mixed", "homogeneous, uniform", "không đồng nhất", "The school has a culturally heterogeneous student body."],
    ["inadvertently", "/ˌɪnədˈvɜːrtəntli/", "ADVERB", "unintentionally, accidentally, mistakenly", "deliberately, intentionally", "vô tình", "I inadvertently deleted the important file."],
    ["intermittent", "/ˌɪntərˈmɪtənt/", "ADJECTIVE", "sporadic, irregular, occasional", "continuous, steady", "gián đoạn", "There was intermittent rain throughout the day."],
    ["manifest", "/ˈmænɪfest/", "VERB/ADJECTIVE", "display, show, obvious", "hide, conceal", "thể hiện, rõ ràng", "His anger manifested itself in his loud voice."],
    ["notwithstanding", "/ˌnɑːtwɪθˈstændɪŋ/", "PREPOSITION/ADVERB", "despite, nevertheless, however", "because of, due to", "mặc dù, bất chấp", "Notwithstanding the bad weather, they decided to go hiking."],
    ["paradox", "/ˈpærədɑːks/", "NOUN", "contradiction, inconsistency, puzzle", "normality, standard", "nghịch lý", "It is a paradox that in such a rich country there is so much poverty."],
    ["precipitate", "/prɪˈsɪpɪteɪt/", "VERB", "trigger, cause, hasten", "delay, block", "gây ra đột ngột", "The assassination precipitated a global war."],
    ["reciprocal", "/rɪˈsɪprəkl/", "ADJECTIVE", "mutual, shared, corresponding", "one-sided, independent", "qua lại, tương hỗ", "They have a reciprocal arrangement to help each other."],
    ["refute", "/rɪˈfjuːt/", "VERB", "disprove, contradict, deny", "prove, support", "bác bỏ", "She strongly refuted the allegations against her."],
    ["stagnant", "/ˈstæɡnənt/", "ADJECTIVE", "inactive, sluggish, still", "active, flowing", "trì trệ", "The stagnant economy has led to high unemployment."],
    ["subordinate", "/səˈbɔːrdɪnət/", "ADJECTIVE", "inferior, secondary, lower", "superior, primary", "thứ yếu", "All other issues are subordinate to this one."],
    ["suppress", "/səˈpres/", "VERB", "subdue, conceal, crush", "encourage, reveal", "ngăn chặn", "The police used tear gas to suppress the riot."],
    ["versatile", "/ˈvɜːrsətl/", "ADJECTIVE", "adaptable, flexible, multifaceted", "limited, inflexible", "đa năng, linh hoạt", "He is a highly versatile actor who can play any role."],

    # Image 3
    ["incremental", "/ˌɪŋkrəˈmentl/", "ADJECTIVE", "gradual, step-by-step, progressive", "sudden, abrupt", "tăng dần từng bước", "The company made incremental improvements to the product."],
    ["induce", "/ɪnˈduːs/", "VERB", "cause, produce, provoke", "prevent, deter", "gây ra", "The medication can induce drowsiness."],
    ["inevitable", "/ɪnˈevɪtəbl/", "ADJECTIVE", "unavoidable, inescapable, certain", "avoidable, uncertain", "không thể tránh khỏi", "It was inevitable that they would lose the game."],
    ["infer", "/ɪnˈfɜːr/", "VERB", "deduce, conclude, gather", "state, express", "suy ra", "From the evidence, we can infer that he is guilty."],
    ["inhibit", "/ɪnˈhɪbɪt/", "VERB", "hinder, restrain, prevent", "encourage, facilitate", "kìm hãm", "Fear of failure can inhibit people from trying new things."],
    ["inherent", "/ɪnˈhɪrənt/", "ADJECTIVE", "intrinsic, innate, built-in", "acquired, external", "vốn có", "There are inherent risks associated with this surgery."],
    ["integrate", "/ˈɪntɪɡreɪt/", "VERB", "combine, merge, unite", "separate, divide", "tích hợp", "The new system is fully integrated with our existing software."],
    ["interpret", "/ɪnˈtɜːrprət/", "VERB", "explain, translate, understand", "misunderstand, confuse", "diễn giải", "It is difficult to interpret the results of the study."],
    ["intrinsic", "/ɪnˈtrɪnzɪk/", "ADJECTIVE", "inherent, fundamental, basic", "extrinsic, acquired", "nội tại, vốn có", "Education has intrinsic value beyond its economic benefits."],
    ["intricate", "/ˈɪntrɪkət/", "ADJECTIVE", "complex, complicated, detailed", "simple, straightforward", "phức tạp, tinh vi", "The watch has an intricate mechanism."],
    ["justify", "/ˈdʒʌstɪfaɪ/", "VERB", "defend, explain, validate", "condemn, attack", "chứng minh là hợp lý", "How can you justify spending so much money on a car?"],
    ["latent", "/ˈleɪtnt/", "ADJECTIVE", "hidden, dormant, concealed", "active, obvious", "tiềm ẩn", "The virus can remain latent in the body for years."],
    ["legitimate", "/lɪˈdʒɪtɪmət/", "ADJECTIVE", "legal, lawful, valid", "illegal, invalid", "hợp pháp, chính đáng", "He has a legitimate claim to the property."],
    ["magnitude", "/ˈmæɡnɪtuːd/", "NOUN", "scale, size, importance", "insignificance, triviality", "độ lớn, quy mô", "They did not fully realize the magnitude of the problem."],
    ["marginal", "/ˈmɑːrdʒɪnl/", "ADJECTIVE", "slight, minor, insignificant", "significant, major", "nhỏ, không đáng kể", "The new tax policy will have only a marginal effect on inflation."],
    ["mediate", "/ˈmiːdieɪt/", "VERB", "arbitrate, intercede, moderate", "provoke, agitate", "điều tiết, làm trung gian", "The UN was asked to mediate in the conflict."],
    ["mitigate", "/ˈmɪtɪɡeɪt/", "VERB", "alleviate, reduce, lessen", "aggravate, worsen", "giảm nhẹ", "Measures need to be taken to mitigate the environmental impact."],
    ["modify", "/ˈmɑːdɪfaɪ/", "VERB", "alter, change, adjust", "maintain, preserve", "điều chỉnh", "We had to modify the original design."],
    ["negligible", "/ˈneɡlɪdʒəbl/", "ADJECTIVE", "insignificant, minor, trivial", "significant, substantial", "không đáng kể", "The difference between the two prices is negligible."],
    ["objective", "/əbˈdʒektɪv/", "ADJECTIVE/NOUN", "impartial, unbiased, goal", "subjective, biased", "khách quan, mục tiêu", "We need an objective assessment of the situation."],
    ["obscure", "/əbˈskjʊr/", "ADJECTIVE/VERB", "unclear, hide, conceal", "clear, reveal", "khó hiểu, che khuất", "The true meaning of the poem remains obscure."],
    ["offset", "/ˈɔːfset/", "VERB", "counterbalance, compensate, make up for", "increase, add", "bù đắp", "The price increase was offset by a reduction in tax."],
    ["paradigm", "/ˈpærədaɪm/", "NOUN", "model, pattern, framework", "anomaly, deviation", "mô hình tư duy, hệ hình", "The war brought about a shift in the political paradigm."],
    ["parameter", "/pəˈræmɪtər/", "NOUN", "limit, boundary, framework", "variable", "tham số, giới hạn", "We have to operate within the parameters set by the budget."],
    ["pervasive", "/pərˈveɪsɪv/", "ADJECTIVE", "widespread, prevalent, ubiquitous", "rare, localized", "lan rộng, phổ biến", "There is a pervasive feeling of pessimism in the country."],
    ["plausible", "/ˈplɔːzəbl/", "ADJECTIVE", "believable, reasonable, credible", "unlikely, impossible", "hợp lý, đáng tin", "Her story sounded perfectly plausible."],
    ["preliminary", "/prɪˈlɪmɪneri/", "ADJECTIVE", "initial, introductory, preparatory", "final, concluding", "sơ bộ", "The preliminary results of the survey are very encouraging."],
    ["prevalent", "/ˈprevələnt/", "ADJECTIVE", "widespread, common, pervasive", "rare, uncommon", "phổ biến", "This belief is prevalent among young people."],
    ["profound", "/prəˈfaʊnd/", "ADJECTIVE", "deep, intense, significant", "superficial, mild", "sâu sắc, rất lớn", "The invention had a profound impact on society."],
    ["prominent", "/ˈprɑːmɪnənt/", "ADJECTIVE", "noticeable, important, famous", "obscure, unknown", "nổi bật", "The issue of climate change was prominent in the debate."],
    ["coexist", "/ˌkoʊɪɡˈzɪst/", "VERB", "live together, exist together", "clash, conflict", "cùng tồn tại", "Different cultures can coexist peacefully in the same society."],
    ["consolidate", "/kənˈsɑːlɪdeɪt/", "VERB", "strengthen, unite, combine", "weaken, separate", "củng cố, hợp nhất", "The company is planning to consolidate its operations."],
    ["contrary", "/ˈkɑːntreri/", "ADJECTIVE/NOUN", "opposite, conflicting, opposed", "similar, agreeing", "trái ngược", "Contrary to popular belief, bats are not blind."],
    ["deplete", "/dɪˈpliːt/", "VERB", "exhaust, empty, drain", "replenish, fill", "làm cạn kiệt", "Our natural resources are being rapidly depleted."],
    ["depict", "/dɪˈpɪkt/", "VERB", "describe, illustrate, portray", "conceal, hide", "miêu tả", "The painting depicts a beautiful landscape."],
    ["disparity", "/dɪˈspærəti/", "NOUN", "difference, inequality, gap", "equality, similarity", "sự chênh lệch", "There is a growing disparity between the rich and the poor."],
    ["ecological", "/ˌiːkəˈlɑːdʒɪkl/", "ADJECTIVE", "environmental, biological, green", "un-environmental", "thuộc sinh thái", "The project was abandoned due to its ecological impact."],
    ["equilibrium", "/ˌiːkwɪˈlɪbriəm/", "NOUN", "balance, stability, symmetry", "imbalance, instability", "trạng thái cân bằng", "The economy has reached a state of equilibrium."],
    ["exert", "/ɪɡˈzɜːrt/", "VERB", "apply, exercise, use", "rest, relax", "tác động, gây ảnh hưởng", "Parents can exert a strong influence on their children."],
    ["foresee", "/fɔːrˈsiː/", "VERB", "anticipate, predict, expect", "ignore, overlook", "dự đoán trước", "I don't foresee any major problems with the project."],
    ["interrelated", "/ˌɪntərɪˈleɪtɪd/", "ADJECTIVE", "connected, linked, associated", "unrelated, separate", "có liên quan lẫn nhau", "These two issues are closely interrelated."],
    ["marginalise", "/ˈmɑːrdʒɪnəlaɪz/", "VERB", "sideline, alienate, exclude", "include, integrate", "gạt ra bên lề", "Minority groups often feel marginalized in society."],
    ["predominant", "/prɪˈdɑːmɪnənt/", "ADJECTIVE", "main, chief, principal", "minor, subordinate", "chủ đạo", "The predominant color in the painting is blue."],
    ["proliferate", "/prəˈlɪfəreɪt/", "VERB", "multiply, rapidly increase, grow", "decrease, decline", "gia tăng nhanh", "Fast-food restaurants have proliferated in recent years."],
    ["recur", "/rɪˈkɜːr/", "VERB", "repeat, happen again, return", "stop, halt", "tái diễn", "This problem tends to recur every few months."],
    ["repercussion", "/ˌriːpərˈkʌʃn/", "NOUN", "consequence, effect, aftermath", "cause, reason", "hậu quả kéo dài", "The decision will have serious repercussions for the company."],
    ["safeguard", "/ˈseɪfɡɑːrd/", "VERB/NOUN", "protect, defend, shield", "endanger, expose", "bảo vệ, biện pháp bảo vệ", "We must implement measures to safeguard our personal data."],
    ["synthesise", "/ˈsɪnθəsaɪz/", "VERB", "combine, blend, integrate", "separate, analyze", "tổng hợp", "The report synthesises data from various sources."],
    ["advocacy", "/ˈædvəkəsi/", "NOUN", "support, promotion, backing", "opposition, resistance", "sự ủng hộ, vận động", "She is known for her strong advocacy of human rights."],
    ["cohesive", "/koʊˈhiːsɪv/", "ADJECTIVE", "united, connected, unified", "divided, fragmented", "gắn kết, mạch lạc", "The team needs to be a cohesive unit to succeed."],
    ["connotation", "/ˌkɑːnəˈteɪʃn/", "NOUN", "implication, underlying meaning, nuance", "denotation, literal meaning", "hàm ý", "The word 'boss' has a negative connotation for some people."],
    ["counterproductive", "/ˌkaʊntərprəˈdʌktɪv/", "ADJECTIVE", "harmful, damaging, self-defeating", "productive, beneficial", "phản tác dụng", "Punishing the child too harshly can be counterproductive."],
    ["delineate", "/dɪˈlɪnieɪt/", "VERB", "describe, outline, define", "confuse, distort", "xác định, mô tả rõ", "The boundaries of the property are clearly delineated."],
    ["endogenous", "/enˈdɑːdʒənəs/", "ADJECTIVE", "internal, inherent", "exogenous, external", "nội sinh", "The changes were caused by endogenous factors within the system."],
    ["exogenous", "/ekˈsɑːdʒənəs/", "ADJECTIVE", "external, outside", "endogenous, internal", "ngoại sinh", "The economy was hit by an exogenous shock."],
    ["hierarchical", "/ˌhaɪəˈrɑːrkɪkl/", "ADJECTIVE", "stratified, ranked, ordered", "egalitarian, equal", "có tính thứ bậc", "The army has a rigid hierarchical structure."],
    ["incompatible", "/ˌɪnkəmˈpætəbl/", "ADJECTIVE", "conflicting, mismatched, clashing", "compatible, harmonious", "không tương thích", "Their working styles are completely incompatible."],
    ["indispensable", "/ˌɪndɪˈspensəbl/", "ADJECTIVE", "essential, crucial, necessary", "dispensable, unnecessary", "không thể thiếu", "Cars have become an indispensable part of our lives."],
    ["nuanced", "/ˈnuːɑːnst/", "ADJECTIVE", "subtle, delicate, refined", "simple, straightforward", "có sắc thái tinh tế", "Her performance was highly nuanced and emotional."],
    ["overarching", "/ˌoʊvərˈɑːrtʃɪŋ/", "ADJECTIVE", "comprehensive, all-embracing, overall", "specific, narrow", "bao quát, tổng thể", "The overarching theme of the conference was sustainability."]
]

columns = ['Term', 'Phonetic', 'PartOfSpeech', 'Synonyms', 'Antonyms', 'Meaning', 'Example']
df = pd.DataFrame(data, columns=columns)

output_dir = r'd:\Agent-skills\english\outputs'
os.makedirs(output_dir, exist_ok=True)
output_file = os.path.join(output_dir, 'vocab_from_images.xlsx')

try:
    df.to_excel(output_file, index=False)
    print(f"Exported {len(data)} words to {output_file}")
except PermissionError:
    alt_file = os.path.join(output_dir, 'vocab_from_images_updated.xlsx')
    df.to_excel(alt_file, index=False)
    print(f"File locked. Exported {len(data)} words to {alt_file}")
